server:
    port: 8383
    context-path: /permission
spring:
    datasource:
        name: ShiroJwt
        url: jdbc:mysql://148.70.156.132:3306/permission?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Qwas#$zx1278
        # 使用Druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            connection-test-query: SELECT 1
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    # 404交给异常处理器处理
    mvc:
        throw-exception-if-no-handler-found: true
    # 404交给异常处理器处理
    resources:
        add-mappings: false
    application:
        name: /permission

mybatis:
    # Mybatis配置Mapper路径
    mapper-locations: classpath:mapper/*.xml
    # Mybatis配置Model类对应
    #type-aliases-package: com.meishutech.permission.model

pagehelper:
    params: count=countSql
    # 指定分页插件使用哪种方言
    helper-dialect: mysql
    # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
    reasonable: 'true'
    support-methods-arguments: 'true'

mapper:
    # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
    not-empty: true
    # Debug打印SQL
logging:
    level:
        com.meishutech.permission.mapper: debug
        org:
            springframework: info
        spring:
            springboot:
                mapper: info
        com:
            # smart: info
            meishutech: info